version: '3.5'

services:
    spark-master:
        image: spark
        command: /spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        hostname: spark-master
        environment:
          SPARK_MASTER: spark://spark-master:7077
          SPARK_PUBLIC_DNS: 127.0.0.1
        ports:
          - 7077:7077
          - 8080:8080
          - 6066:6066
        volumes:
          - ./data:/data/
        networks: 
            spark_nw: 
                ipv4_address: 10.5.0.5

    spark-worker-1:
        image: spark
        depends_on:
          - spark-master
        command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        hostname: spark-worker-1
        environment:
          SPARK_MASTER: spark://spark-master:7077
          SPARK_WORKER_CORES: 1
          SPARK_WORKER_MEMORY: 1g
          SPARK_WORKER_PORT: 8881
          SPARK_WORKER_WEBUI_PORT: 8081
          SPARK_PUBLIC_DNS: 127.0.0.1
        ports:
          - 8081:8081
        volumes:
          - ./data:/data/
        networks: 
          - spark_nw 

networks: 
    spark_nw: 
        name: spark_nw
        driver: overlay 
        attachable: true
        ipam:
            driver: default 
            config: 
              - subnet: 10.5.0.0/24 
